title: 台北市召會43會所 1-2小區
description: "神人調和，繁茂復活."
logo_img: "/assets/img/favicon.png"
profile_img: "/assets/img/profile.webp"

# Social Links
email:
github_username: cit-hall-43
twitter_username:
instagram_username:
linkedin_username:
facebook_username:
line_id: 685lhtvb

# External API
giscus_repo: "cit-hall-43/cit-hall-43.github.io"
giscus_repoId: "R_kgDOMMsGHA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOMMsGHM4CgqXM"
goatcounter_code: cit-hall-43
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
